# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

# container_scanning:
#   variables:
#     DOCKER_IMAGE: ...
#     DOCKER_USER: ...
#     DOCKER_PASSWORD: ...
image: registry.gitlab.com/s0j0hn/go-rest-boilerplate-echo:latest
cache:
  paths:
  - "/apt-cache"
  - "/go/src/github.com"
  - "/go/src/golang.org"
  - "/go/src/google.golang.org"
  - "/go/src/gopkg.in"
stages:
- build
- test
- sast
before_script:
- mkdir -p /go/src/gitlab.com/s0j0hn /go/src/_/builds
- cp -r $CI_PROJECT_DIR /go/src/gitlab.com/s0j0hn/go-rest-boilerplate-echo
- ln -s /go/src/gitlab.com/s0j0hn /go/src/_/builds/s0j0hn
- export CC=clang
unit_tests:
  stage: test
  except:
  - tags
  allow_failure: true
  retry: 2
  script:
  - make dep
  - make test
code_coverage:
  stage: test
  script:
  - make coverage
build:
  stage: build
  except:
  - tags
  script:
  - go get -u github.com/swaggo/swag/cmd/swag
  - make dep
  - make build
include:
- template: Security/SAST.gitlab-ci.yml
- template: Jobs/Container-Scanning.gitlab-ci.yml
variables:
  SAST_EXPERIMENTAL_FEATURES: 'true'
