version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-boilerplate}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-boilerplate}
      POSTGRES_DB: ${POSTGRES_DB:-boilerplate}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: overlay

volumes:
  postgres:
