basePath: /
definitions:
  handlers.errorResult:
    properties:
      message:
        type: string
    type: object
  handlers.postTenantData:
    properties:
      id:
        type: string
      name:
        type: string
    required:
    - id
    - name
    type: object
  handlers.resultJson:
    properties:
      id:
        type: string
      name:
        type: string
    required:
    - id
    - name
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Boilerplate API
  version: "1.0"
paths:
  /tenants:
    get:
      consumes:
      - application/json
      description: get tenants
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.resultJson'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResult'
      summary: List tenants
      tags:
      - tenants
    post:
      consumes:
      - application/json
      description: create by json tenant
      parameters:
      - description: Add tenant
        in: body
        name: tenant
        required: true
        schema:
          $ref: '#/definitions/handlers.postTenantData'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.resultJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResult'
      summary: Create a tenant
      tags:
      - tenants
    put:
      consumes:
      - application/json
      description: update by json tenant
      parameters:
      - description: Update tenant
        in: body
        name: tenant
        required: true
        schema:
          $ref: '#/definitions/handlers.postTenantData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.resultJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResult'
      summary: Update a tenant
      tags:
      - tenants
  /tenants/{id}:
    delete:
      description: delete tenant by id
      operationId: delete-tenant-by-id
      parameters:
      - description: Tenant Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.resultJson'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResult'
      summary: Delete tenant
      tags:
      - tenants
    get:
      consumes:
      - application/json
      description: get tenant by id
      operationId: get-tenant-by-id
      parameters:
      - description: Tenant Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.resultJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResult'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResult'
      summary: Show a tenant info
      tags:
      - tenants
swagger: "2.0"
